name: Scan

on:
  workflow_dispatch:
  schedule:
    # Scan the image regularly (once a day)
    - cron: '0 22 * * *'

jobs:
  scan:
    name: Scan current image & report results
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/mce0/chrony'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          vuln-type: "os"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
